Handle ESC like Acme
rjkroege/edwood pull request #341
Opened 2021-07-02 00:18 UTC by dnjp

After typing text in Acme, one can press ESC to select the previously typed text and press ESC again to delete it. This is possible because `eq0` [is set when typing begins](https://github.com/9fans/plan9port/blob/70cc6e5ba7798b315c3fb3aae19620a01604a459/src/cmd/acme/text.c#L910) and is checked for [when ESC is pressed](https://github.com/9fans/plan9port/blob/70cc6e5ba7798b315c3fb3aae19620a01604a459/src/cmd/acme/text.c#L836). This PR adds support for this feature by setting `eq0` to the first address (0) when text is typed in a similar manner as is done in Acme.

2021-07-02 23:58 UTC, rjkroege requested changes
Thanks for fixing this bug. Would you mind changing the constant?

2021-07-02 23:58 UTC, rjkroege commented on text.go
> +	if t.eq0 == ^0 {
I'd prefer `-1` instead of `^0`.

2021-07-03 01:28 UTC, dnjp commented on text.go
> +	if t.eq0 == ^0 {
Not a problem. Just pushed the change.

2021-07-03 23:22 UTC, rjkroege approved these changes

2021-07-03 23:33 UTC, merged