Refactored so that OEB has a diskdetails rather than file
rjkroege/edwood pull request #342
Opened 2021-07-21 18:20 UTC by camsn0w

Refactored so ObservableEditableBuffer now has filename, hash, etc to work to separate functionality out of file for #97 #334

2021-07-22 00:42 UTC, rjkroege requested changes
Review comments:

In `pfilename()`: 

```go
if curtext != nil && curtext.file.Equal([]rune(f.String())) {
```

why did you turn a pointer equality test into a rune-by-rune
comparison?

In `elog.go`: all changes of `text` to `observer` need to be reverted.

In `file.go`: can you remove `File.SaveableAndDirty` and then you
don't need to reach back into `oeb` for the `Name`.

`File.Load` has a forwarding function. You can move

```go
if sethash {
	f.oeb.SetHash(file.CalcHash(d))
}
```

into the `ObservableEditableBuffer` and avoid reaching back into the `oeb`.

You should consider pulling `setnameandisscratch` out of `file.go`. Yes, you'll
have to reach into it from `Undo` but that's temporary until you write the improved
`Undo` wrapper for `undo.Buffer`.

In `fsys_test.go`, revert the `text` to `observers` change.

In `logf.go`, change to `xfidlog()` looks unnecessary?

In `regx.go`: revert change of `observers` to `text`.

Same in `rune_array.go`

Same in util.go:/flushwarnings

2021-07-22 19:05 UTC, camsn0w commented
> Review comments:
> 
> In `pfilename()`:
> 
> ```go
> if curtext != nil && curtext.file.Equal([]rune(f.String())) {
> ```
> 
> why did you turn a pointer equality test into a rune-by-rune
> comparison?
resolved
> 
> In `elog.go`: all changes of `text` to `observer` need to be reverted.
resolved
> 
> In `file.go`: can you remove `File.SaveableAndDirty` and then you
> don't need to reach back into `oeb` for the `Name`.
resolved with question
> 
> `File.Load` has a forwarding function. You can move
> 
> ```go
> if sethash {
> 	f.oeb.SetHash(file.CalcHash(d))
> }
> ```
> 
> into the `ObservableEditableBuffer` and avoid reaching back into the `oeb`.
> 
maybe resovled, doing so moves most of Load to OEB, is this correct?
> You should consider pulling `setnameandisscratch` out of `file.go`. Yes, you'll
> have to reach into it from `Undo` but that's temporary until you write the improved
> `Undo` wrapper for `undo.Buffer`.
> 
resolved
> In `fsys_test.go`, revert the `text` to `observers` change.
resolved
> 
> In `logf.go`, change to `xfidlog()` looks unnecessary?
resolved
> 
> In `regx.go`: revert change of `observers` to `text`.
> 
> Same in `rune_array.go`
> 
> Same in util.go:/flushwarnings
resolved

2021-07-28 13:36 UTC, rjkroege commented
Review comments to the end of 5868cb2

* *observation* `file.go:222` makes temporary copies of entire loaded
buffers. This is oviously not ideal. Someone (me?) should fix this.
There's already a bunch of TODOs here.

* `file.go:377` is a layering issue that you will need to fix in a
future CL. `undo.Buffer` won't track changes to the file name. I
propose that you address this in your next CL.

* `file.go:507` has the same issue. The `Undo` wrapper in
`observableeditablebuffer.go` needs to handle `Undo` ops on the
filename. (Perhaps the logic of backing disk file naming mostly
belongs in the disk details.)

* Some future CL should rename `observableeditablebuffer.go` to
`observable_editable_buffer.go`. The idiomatic naming pattern: if the
type is `RuneArray`, the file should be `rune_array.go`.

* `observableeditablebuffer.go:329`: another future CL needs to move
`isscratch` into either `ObservableEditableBuffer` or `DiskDetails` --
`isscratch` tracks an attribute of the disk file.

2021-07-28 13:38 UTC, rjkroege approved these changes

2021-07-28 13:38 UTC, merged